Fix npm plugin permission denied
snapcore/snapcraft pull request #3624
Opened 2022-01-14 17:21 UTC by om26er

- [*] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [*] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `./runtests.sh static`?
- [*] Have you successfully run `./runtests.sh tests/unit`?

-----

Since snapcraft in lxd/multipass is run as root user, there can be cases where the installation of npm packages fails with "permission denied". This issue has been lurking around for a long time and there isn't really a workaround apart from not using the npm plugin and shipping npm in a custom part.

The reason for that is that npm plugin's `get_build_commands` method downloads npm from upstream and then in the next command calls `npm install` and `npm pack`, leaving no way for the developers to configure npm at all.

Here is one related issue https://forum.snapcraft.io/t/issue-with-nodejs-plugin-when-using-base-keyword/11109/14

2022-01-14 17:22 UTC, om26er commented
We depend heavily on snapcraft/snapd and have a number of node based apps that face this specific issue. Currently we ship our own copy of node as a separate part because of this issue.

2022-01-15 12:59 UTC, sergiusens approved these changes

2022-01-15 13:01 UTC, sergiusens requested changes
test might need update, while you are at it, mind amending the commit to be something like:

`npm plugin: allow running as root`

Please refer to https://github.com/snapcore/snapcraft/blob/main/CONTRIBUTING.md#snapcraft-contribution-guide

2022-01-15 20:27 UTC, om26er commented
> test might need update, while you are at it, mind amending the commit to be something like:

done, both. Please take a look again

2022-01-16 09:08 UTC, om26er commented
This unit test is fixed now

2022-01-17 14:36 UTC, sergiusens approved these changes

2022-01-17 14:37 UTC, merged

2022-01-17 14:37 UTC, sergiusens commented
Thank you!!!!