ROS plugins v2: respect source-subdir key
snapcore/snapcraft pull request #3664
Opened 2022-03-15 14:19 UTC by Guillaumebeuzeboc

Update comment

Remove useless dependency in catkin_tools.
Now python3-osrf-pycommon is an explicit dependency of
python3-catkin-tools
see:
http://packages.ros.org/ros/ubuntu/dists/focal/main/binary-amd64/Packages

Use source-subdir for rosdeps dependencies pull

Use source-subdir for ROS plugins v2

Adapt test to match new ROS tools v2 source-subdir use

Add test for Colcon V2 subdir usage

Add tests for catkin/catkin-tools V2 subdir usage

- [X] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [X] Have you successfully run `./runtests.sh static`?
- [X] Have you successfully run `./runtests.sh tests/unit`?

-----

2022-03-15 14:19 UTC, Guillaumebeuzeboc commented
@artivis

2022-03-16 08:04 UTC, Guillaumebeuzeboc commented
I had to sign the CLA even with my canonical email. Now it's done.

2022-03-16 14:27 UTC, artivis requested changes

2022-03-16 14:27 UTC, artivis commented on tests/spread/plugins/v2/snaps/catkin-noetic-subdir/subdir/src/CMakeLists.txt
> +/opt/ros/noetic/share/catkin/cmake/toplevel.cmake
File committed by mistake?

2022-03-16 14:27 UTC, artivis commented on tests/spread/plugins/v2/snaps/catkin-noetic-hello/src/CMakeLists.txt
> +/opt/ros/noetic/share/catkin/cmake/toplevel.cmake
File committed by mistake?

2022-03-16 14:27 UTC, artivis commented on tests/spread/plugins/v2/snaps/catkin-tools-noetic-subdir/subdir/src/snapcraft_hello/src/hello.cpp
> +// Copyright (C) 2020 Canonical Ltd
There are a few places where the license need a fix (some `package.xml`). Make sure to use `GPLv3`.

2022-03-16 16:42 UTC, Guillaumebeuzeboc commented on tests/spread/plugins/v2/snaps/catkin-tools-noetic-subdir/subdir/src/snapcraft_hello/src/hello.cpp
> +// Copyright (C) 2020 Canonical Ltd
updated with 2022 copyright and GPLv3

2022-03-18 19:09 UTC, sergiusens approved these changes

2022-03-18 19:10 UTC, merged