cli: update craft-cli to comply with UX guidelines
snapcore/snapcraft pull request #3833
Opened 2022-07-07 22:48 UTC by cmatsuoka

Craft-cli 1.0.0 updates CLI verbosity levels to follow the UX standard
to be used across *craft tools. It makes output to stdout and stderr more
consistent and makes the verbose output less verbose by removing debug
messages and timestamps.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----
CRAFT-1144

2022-07-07 22:59 UTC, sergiusens approved these changes

2022-07-07 23:00 UTC, sergiusens requested changes
looks really good, missing the hidden -t/--trace option as we managed to release with that.

2022-07-08 00:18 UTC, cmatsuoka commented
Added hidden `-t`/`--trace` global arguments to use debug mode; show deprecation warning.

2022-07-08 12:13 UTC, sergiusens approved these changes

2022-07-08 12:13 UTC, merged