DT-500 Fix Cups for Gtk support in Gnome-42
snapcore/snapcraft pull request #3867
Opened 2022-08-10 14:21 UTC by sergio-costas

The printing support in Gtk is supported by several DLLs located
at /usr/lib/TRIPLET/gtk-X.0 (being X equal to 3 or 4).
Unfortunately, that wasn't configured in the layout for Gnome-42,
so some GTK programs (like gnome-text-editor) crashed when trying
to print something.

This MR fixes this by doing a symlink for both folders. It also
changes all the other bindings into symlinks, because of
https://bugs.launchpad.net/snapd/+bug/1983589 (sometimes, the
folders aren't binded).

- [X] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [X] Have you successfully run `make lint`?
- [X] Have you successfully run `pytest tests/unit`?

-----

2022-08-10 14:22 UTC, sergio-costas commented
I still have to discuss with @sergiusens and @kenvandine if it is a good idea to replace the "bind"s with "symlink"s. But at this moment it seems the only solution.

2022-08-10 15:04 UTC, kenvandine approved these changes
Looks good to me, thanks!

2022-08-11 09:00 UTC, jhenstridge requested changes
For what it is worth, we have a few environment variables that can control how GTK finds its modules:

https://docs.gtk.org/gtk4/running.html#gtk_path
https://docs.gtk.org/gtk4/running.html#gtk_exe_prefix

We are already setting `GTK_PATH` to point at GTK 3 modules in the `desktop-launch` script:

https://github.com/snapcore/snapcraft/blob/00e0ce47864fb09e75eb6325f009ff6dbabb1c09/extensions/desktop/gnome/launcher-specific#L13

... so would also appending the 4.0 module path solve the problem here?

The gtk-4.0 directory in gnome-42-2204 only contains a versioned subdir, so shouldn't cause problems for GTK 3 apps.

2022-08-11 09:02 UTC, sergio-costas commented on snapcraft/extensions/gnome.py
> +                    "symlink": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gtk-4.0"
Yes, I'm changing it due to this: https://bugs.launchpad.net/snapd/+bug/1983589

2022-08-11 09:59 UTC, jhenstridge approved these changes
Looks good. Adding the gtk-2.0 directory is probably fine. The only unversioned module in that directory is libatk-bridge.so, which GTK 3 and GTK 4 blacklist.

2022-08-11 10:49 UTC, sergio-costas commented on snapcraft/extensions/gnome.py
> +                    "symlink": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gtk-4.0"
After discussing it with James in mattermost, it makes sense to not change binds into symlinks.

2022-08-26 20:46 UTC, merged