kernel plugin initramfs: don't copy extra-modules.conf
snapcore/snapcraft pull request #3973
Opened 2022-11-03 17:06 UTC by mbd98

Fixes failure to copy due to non-existent source file. Source file no longer exists upstream, and intended target already exists. See https://github.com/snapcore/core-initrd/tree/main/modules

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [x] Have you successfully run `pytest tests/unit`?

-----

2022-11-07 07:31 UTC, sergiusens approved these changes

2022-11-17 12:59 UTC, sergiusens requested changes
tests have not been updated

2022-12-01 01:54 UTC, sergiusens approved these changes

2022-12-01 01:56 UTC, merged

2022-12-06 17:49 UTC, kubiko commented
@sergiusens @mbd98 I'm late here and I will revert this PR in #3998
Anyway, this PR might have fixed a build error if there are not defined kernel modules to be included in the initramfs, but it also causes regression, that if there are defined kernel modules to be included, now they are not.
This change also renders for loop in `_make_initrd_cmd` useless. That loop populates `${initramfs_ko_modules_conf}` with requested kernel modules. If we do not copy the populated file, those won't be included.

The correct fix is to always create an empty file.