requirements: pin setuptools<66
snapcore/snapcraft pull request #4031
Opened 2023-02-07 18:28 UTC by mr-cal

- [X] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [X] Have you successfully run `make lint`?
- [X] Have you successfully run `pytest tests/unit`?

-----

[`setuptools>=66`](https://setuptools.pypa.io/en/stable/history.html#v66-0-0) enforces versioning requirements from [PEP 440](https://peps.python.org/pep-0440/), which causes some of the unit tests to fail.

Added comments and a TODO so it can be resolved in the future.

2023-02-07 18:44 UTC, tigarmo approved these changes

2023-02-07 18:48 UTC, cmatsuoka approved these changes

2023-02-07 19:00 UTC, lengau requested changes

2023-02-07 19:00 UTC, lengau commented on tests/unit/elf/test_elf_file.py
> +    # TODO: The `fake_elf` fixture does not set proper versions and causes this
I think the best thing to do is to put the `TODO` into `get_required_glibc`. If you can create a JIRA ticket and reference that ticket number too, that'd be sufficient documentation IMO.

2023-02-07 19:30 UTC, mr-cal commented on tests/unit/elf/test_elf_file.py
> +    # TODO: The `fake_elf` fixture does not set proper versions and causes this
:heavy_check_mark:

2023-02-07 22:42 UTC, merged

2023-02-16 01:50 UTC, OzVazquez approved these changes