requirements: update craft-parts to 1.21.0
snapcore/snapcraft pull request #4183
Opened 2023-05-30 18:07 UTC by cmatsuoka

Craft Parts 1.21.0 add callbacks to explicitly list base packages
and to configure the overlay package layer.

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----

2023-05-31 20:05 UTC, lengau approved these changes

2023-05-31 21:06 UTC, sergiusens requested changes
unit tests need updating for this to take into account pyproject.toml

2023-06-05 18:15 UTC, cmatsuoka commented
Rebased on main.

2023-06-06 19:48 UTC, sergiusens approved these changes

2023-06-06 19:48 UTC, merged