Various Fixes for Gnome SDK
snapcore/snapcraft pull request #4391
Opened 2023-10-04 14:45 UTC by soumyaDghosh

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you successfully run `make lint`?
- [ ] Have you successfully run `pytest tests/unit`?

-----
## Changes:
- The gnome-sdk has webkit2gtk-4.1 files, but it also needs a layout just like webkit2gkt-4.0. 
- Changed the `SNAPCRAFT` in the layouts to `CRAFT`
- Updated description[Gnome SDK now has Gnome-45 libraries also]
- Added `GDK_DEBUG=portals` in environment. Needed by apps to open the file chooser portal. Examples: `clapper`, `metadata-cleaner`, `fragments`.

Run these apps with `GDK_DEBUG=portals` and without to see the file chooser changes.

2023-10-05 15:11 UTC, kenvandine commented on snapcraft/extensions/gnome.py
> +                "GDK_DEBUG": "portals",
I'd separate this as it's unrelated to the other changes in the PR.  Also, I'm not confident of the implications we'll have across the wide range of snaps we have using the extension, so I'd say it's a pretty risky change.

2023-10-05 16:22 UTC, sergio-costas approved these changes
LGTM, although it seems that the linter has some complains...

2023-10-06 17:27 UTC, sergiusens requested changes
you have not changed any unit tests, I would make 2 PRs, one for the text change and another for the layout changes

2023-10-06 17:40 UTC, soumyaDghosh commented
> you have not changed any unit tests, I would make 2 PRs, one for the text change and another for the layout changes

Should I close this PR then?

2023-11-13 12:30 UTC, sergiusens commented
> > you have not changed any unit tests, I would make 2 PRs, one for the text change and another for the layout changes
> 
> Should I close this PR then?

what I mean is that this PR is failing as you changed code but not their related unit tests

2023-11-13 12:31 UTC, sergiusens commented
if you want to close and create two new from scratch PRs go ahead, or trim this down to one thing (the text change perhaps)

2023-11-17 12:55 UTC, soumyaDghosh commented
recreating this PR, with some added changes

2023-11-17 12:56 UTC, closed without merging