chore(log): hide details error in the log when pack failed
snapcore/snapcraft pull request #4424
Opened 2023-10-25 21:14 UTC by syu-w

The error will looks like this instead of long stderr output.
```
Command '['snap', 'pack', '--check-skeleton', PosixPath('/root/prime')]' returned non-zero exit status 1.
Failed to execute pack in instance.
```

The stderr output will be saved in the logs.

2023-10-26 21:06 UTC, syu-w commented
Falling tests unrelated.

2023-10-27 14:41 UTC, syu-w commented on snapcraft/parts/lifecycle.py
> +            if err.stderr:
hmmm, that could work

2023-10-27 15:50 UTC, mr-cal commented on snapcraft/parts/lifecycle.py
> +                details=details,
```diff
-details = None
-if err.stderr:
-    details = err.stderr.strip()
raise errors.SnapcraftError(
    f"Failed to execute {command_name} in instance.",
-    details=details,
+    details=err.stderr.strip() if err.stderr else None,
```

2023-10-27 15:55 UTC, syu-w commented on snapcraft/parts/lifecycle.py
> +                details=details,
Done

2023-10-27 16:50 UTC, mr-cal approved these changes
:+1:

2023-10-31 08:24 UTC, sergiusens requested changes
it is exactly the opposite that we want, we need to details

So the error should be:

Cannot pack: <the error message from snap pack --check-skeleton>

and in details put in the full command that failed to run

2023-10-31 21:26 UTC, sergiusens approved these changes
nice work!

2023-11-01 10:59 UTC, cmatsuoka approved these changes

2023-11-01 15:15 UTC, merged