Added support for `webkitgtk2-4.0` and added `GI_TYPELIB_PATH` for gi path
snapcore/snapcraft pull request #4451
Opened 2023-11-17 16:53 UTC by soumyaDghosh

- [x] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x] Have you successfully run `make lint`?
- [x] Have you successfully run `pytest tests/unit`?

-----

All the tests are mostly passing, except one fail in the test. Probably not my fault

```
_______________________________________________________________________ test_get_extensions_data_dir ________________________________________________________________________

    def test_get_extensions_data_dir():
>       assert (get_extensions_data_dir() / "desktop").is_dir()
E       AssertionError: assert False
E        +  where False = <bound method Path.is_dir of PosixPath('/home/ubuntu/.venv/snapcraft/share/snapcraft/extensions/desktop')>()
E        +    where <bound method Path.is_dir of PosixPath('/home/ubuntu/.venv/snapcraft/share/snapcraft/extensions/desktop')> = (PosixPath('/home/ubuntu/.venv/snapcraft/share/snapcraft/extensions') / 'desktop').is_dir
E        +      where PosixPath('/home/ubuntu/.venv/snapcraft/share/snapcraft/extensions') = get_extensions_data_dir()

tests/unit/extensions/test_extensions.py:280: AssertionError
```

2023-11-17 22:33 UTC, lengau requested changes

2023-11-17 22:33 UTC, lengau commented on snapcraft/extensions/gnome.py
> +                    "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1"
```suggestion
                "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0": {
                    "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0"
                },
                "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1": {
                    "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1"
```

`CRAFT_ARCH_TRIPLET` will be deprecated in snapcraft 8 :-)

2023-11-17 22:33 UTC, lengau commented on snapcraft/extensions/gnome.py
> +                            f"/snap/{sdk_snap}/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0",
```suggestion
                            f"/snap/{sdk_snap}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0",
```

2023-11-17 22:33 UTC, lengau commented on tests/unit/extensions/test_gnome.py
> +                "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1"
```suggestion
                "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0"
            },
            "/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1": {
                "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1"
```

2023-11-17 22:33 UTC, lengau commented on tests/unit/extensions/test_gnome.py
> +                "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.1"
```suggestion
            "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0": {
                "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0"
            },
            "/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1": {
                "bind": "$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1"
```

2023-11-17 22:33 UTC, lengau commented on tests/unit/extensions/test_gnome.py
> +                            "/snap/gnome-42-2204-sdk/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0",
```suggestion
                            "/snap/gnome-42-2204-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0",
```

2023-11-17 22:33 UTC, lengau commented on tests/unit/extensions/test_gnome.py
> +                        "/snap/gnome-44-2204-sdk/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0",
```suggestion
                        "/snap/gnome-44-2204-sdk/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0",
```

2023-12-14 21:07 UTC, mr-cal requested changes
Thanks @soumyaDghosh!

It looks like the unit tests for `tests/unit/extensions/test_gnome.py::test_get_root_snippet` are still failing.  Do you mind taking a look?

Also, I see a linter failure for lines that are too long in `snapcraft/extensions/gnome.py` and in the unit tests.  Do you mind breaking those strings into multiple lines to satisfy the linter?

2023-12-16 11:49 UTC, soumyaDghosh commented
@mr-cal The tests should pass now. But regarding the lint, complaining about long lines, I don't think I can help it. Those lines it's saying to break (eg: [159](https://github.com/soumyaDghosh/snapcraft/blob/main/snapcraft/extensions/gnome.py#L159)) should be as they are as much I can think. Kindly give your opinion on it.

2024-02-06 15:37 UTC, mr-cal commented
> @mr-cal The tests should pass now. But regarding the lint, complaining about long lines, I don't think I can help it. Those lines it's saying to break (eg: [159](https://github.com/soumyaDghosh/snapcraft/blob/main/snapcraft/extensions/gnome.py#L159)) should be as they are as much I can think. Kindly give your opinion on it.

The tests look good, thanks.

I think you can satisfy the linter by breaking those strings into multiple lines.  You can cherry-pick this commit if you'd like: https://github.com/snapcore/snapcraft/commit/ab97ec7b8d96b31a8dde6cd5256bd56e180c8641

Otherwise, I'm happy to push that commit and update this branch onto the latest changes on `main`.

2024-02-06 16:07 UTC, soumyaDghosh commented
> 
> The tests look good, thanks.
> 
> I think you can satisfy the linter by breaking those strings into multiple lines.  You can cherry-pick this commit if you'd like: https://github.com/snapcore/snapcraft/commit/ab97ec7b8d96b31a8dde6cd5256bd56e180c8641
> 
> Otherwise, I'm happy to push that commit and update this branch onto the latest changes on `main`.

Sure please push the commit and update this branch. I didn't know it's possible. Thank you.

2024-02-07 15:07 UTC, lengau approved these changes
Looks good, thanks!

2024-02-08 18:17 UTC, merged

2024-02-13 13:23 UTC, sergiusens commented
@mr-cal please watch your merge messaging

2024-02-13 13:31 UTC, mr-cal commented
Whoops, sorry!